/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksShopifyOrdersCreateRouteImport } from './routes/webhooks/shopify/orders/create'

const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksShopifyOrdersCreateRoute =
  WebhooksShopifyOrdersCreateRouteImport.update({
    id: '/webhooks/shopify/orders/create',
    path: '/webhooks/shopify/orders/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/webhooks/shopify/orders/create': typeof WebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/webhooks/shopify/orders/create': typeof WebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/webhooks/shopify/orders/create': typeof WebhooksShopifyOrdersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/webhooks/shopify/orders/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/webhooks/shopify/orders/create'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/webhooks/shopify/orders/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRoute
  WebhooksShopifyOrdersCreateRoute: typeof WebhooksShopifyOrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/shopify/orders/create': {
      id: '/webhooks/shopify/orders/create'
      path: '/webhooks/shopify/orders/create'
      fullPath: '/webhooks/shopify/orders/create'
      preLoaderRoute: typeof WebhooksShopifyOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRoute,
  WebhooksShopifyOrdersCreateRoute: WebhooksShopifyOrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
